### ISSUE TITLE
Uncaught Error: Cannot find module '$ATOM_HOME/packages/highlights'

### ISSUE THREAD

**Issue by boggle** [asciidoctor/atom-asciidoc-preview#187]
This has been broken for ages, would be nice if that could be fixed

[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.8.0
**System**: Mac OS X 10.11.5
**Thrown From**: [asciidoc-preview](https://github.com/asciidoctor/atom-asciidoc-preview) package, v2.4.2

### Stack Trace

Uncaught Error: Cannot find module '/Users/stepup/.atom/packages/highlights'

```
At module.js:340

Error: Cannot find module '/Users/stepup/.atom/packages/highlights'
    at Module._resolveFilename (module.js:338:15)
    at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:289:25)
    at Module.require (module.js:366:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/stepup/.atom/packages/asciidoc-preview/lib/renderer.coffee:7:14)
    at Object.<anonymous> (/Users/stepup/.atom/packages/asciidoc-preview/lib/renderer.coffee:1:1)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/stepup/.atom/packages/asciidoc-preview/lib/asciidoc-preview-view.coffee:8:12)
    at Object.<anonymous> (/Users/stepup/.atom/packages/asciidoc-preview/lib/asciidoc-preview-view.coffee:1:1)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at isAsciiDocPreviewView (/Users/stepup/.atom/packages/asciidoc-preview/lib/main.coffee:11:26)
    at Object.module.exports.toggle (/Users/stepup/.atom/packages/asciidoc-preview/lib/main.coffee:92:8)
    at atom-workspace.subscriptions.add.atom.commands.add.asciidoc-preview:toggle (/Users/stepup/.atom/packages/asciidoc-preview/lib/main.coffee:28:10)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at CommandPaletteView.module.exports.CommandPaletteView.confirmed (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/command-palette/lib/command-palette-view.js:183:32)
    at CommandPaletteView.module.exports.SelectListView.confirmSelection (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:338:21)
    at space-pen-div.atom.commands.add.core:confirm (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:109:19)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:98:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
     -1:17.1.0 core:move-left (atom-text-editor.editor.is-focused)
     -0:40.7.0 core:save (atom-text-editor.editor.is-focused)
     -0:33.9.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:30.9.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:30.7.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -0:30.7.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -0:30.5.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -0:30.5.0 core:cancel (atom-text-editor.editor.is-focused)
     -0:28.4.0 pipe:run (atom-text-editor.editor.is-focused)
     -0:27.7.0 settings-view:open (atom-text-editor.editor.mini.is-focused)
     -0:09.6.0 grammar-selector:show (atom-text-editor.editor)
     -0:07.7.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -0:07.7.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -0:04.2.0 command-palette:toggle (a.inline-block)
     -0:00.9.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:00.9.0 asciidoc-preview:toggle (a.inline-block)
```

### Config

```json
{
  "core": {
    "audioBeep": false,
    "disabledPackages": [
      "haskell-grammar",
      "haskell-unicode-snippets"
    ],
    "ignoredNames": [
      ".git",
      ".svn",
      ".DS_Store"
    ],
    "packagesWithKeymapsDisabled": [
      "ide-haskell"
    ],
    "projectHome": "/Users/stepup/Source",
    "themes": [
      "one-light-ui",
      "solarized-light-syntax"
    ]
  },
  "asciidoc-preview": {}
}
```

### Installed Packages

```coffee
# User
asciidoc-preview, v2.4.2
autocomplete-python, v1.8.1
bracket-matcher, v0.82.1
cucumber, v0.5.0
cursor-history, v0.5.9
emmet, v2.4.3
haskell-pointfree, v0.1.3
ide-haskell-cabal, v1.4.0
imdone-atom, v1.3.29
language-asciidoc, v1.5.1
language-cypher, v0.3.0
language-diff, v0.4.0
language-haskell, v1.7.17
language-java, v0.23.0
language-rust, v0.4.6
language-scala, v1.1.6
linter, v1.11.11
linter-flake8, v1.13.2
linter-hlint, v0.4.3
linter-rust, v0.4.6
markdown-preview, v0.158.0
merge-conflicts, v1.4.4
minimap, v4.24.6
pigments, v0.29.2
pipe, v0.4.0
project-manager, v2.9.7
racer, v0.20.0
tool-bar, v0.4.0
trailing-spaces, v0.3.2
tree-view-git-status, v1.0.0

# Dev
No dev packages
```

**Comment by ldez** [comment]
Hello @boggle,

the problem is already fixed: see #151, #152.

If the problem persist:
1. close Atom
2. `apm uninstall asciidoc-preview`
4. `apm rebuild-module-cache`
5. `apm install asciidoc-preview`
6. open Atom

**Comment by PaulAndersonMule** [comment]
@ldez this is still broken after taking the steps you recommend (preview is broken completely now)

Error: Cannot find module '/Users/paul.anderson/.atom/packages/highlights'
    at Module._resolveFilename (module.js:338:15)
    at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:289:25)
    at Module.require (module.js:366:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/paul.anderson/.atom/packages/asciidoc-preview/lib/renderer.coffee:7:14)
    at Object.<anonymous> (/Users/paul.anderson/.atom/packages/asciidoc-preview/lib/renderer.coffee:1:1)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)

**Comment by ldez** [comment]
`highlights` module is provided by Atom directly.

You can try: `apm install highlights`

**Comment by PaulAndersonMule** [comment]
UPDATE: the "fix" for me was to rm -rf ~/.atom and reinstall everything. Not a confidence builder in what I suspect is the core Atom architecture

(thanks for the 'apm install highlights' suggestion; it fails with 'Request for package information failed: Not Found', but see UPDATE in previous post. )

**Comment by ldez** [comment]
@PaulAndersonMule you speak about  #182 ?

**Comment by ldez** [comment]
@boggle Is that the problem is solved?

**Comment by PaulAndersonMule** [comment]
@ldez no - my earlier comment here was about this one - #187

**Comment by ldez** [comment]
Without response, I close this issue.

**Comment by metasean** [comment]
I'm having the same problem as PaulAndersonMule.

I tried to use @ldez's [Jun 17th suggestion](https://github.com/asciidoctor/atom-asciidoc-preview/issues/187#issuecomment-226726477).  When I run `apm rebuild-module-cache` I get:
```
Rebuilding asciidoc-assistant module cache ✗
Cannot read property 'link' of undefined
```

And I haven't found a way to get a more useful output yet.  

I'm going to keep troubleshooting on my end, but ***this is definitely still an issue***.

**Comment by ldez** [comment]
@metasean the 'highlights' problem is a problem with Atom installation.

The extreme solution:
- uninstall Atom
- `rm -rf ~/.atom`
- Install Atom

For the second problem:
> Rebuilding asciidoc-assistant module cache ✗

It's related to https://github.com/asciidoctor/atom-asciidoc-assistant, please open and issue in the repository if the problem continue after the 'extreme solution'.

**Comment by metasean** [comment]
@ldez - I was afraid that was the next step.  I did manage to avoid having to be quite that extreme.

I installed "[sync-settings](https://atom.io/packages/sync-settings)", did a backup, then tourced my '.atom' directory, installed "sync-settings" again, and then did a reinstall.

I still got an error related to dependencies while installing asciidoc-preview but the error message was particularly generic, so I'm not really sure what the actual problem was.  I ran `apm install asciidoc-preview` and it installed without error. I can now see previews without any apparent problems.

**Comment by ldez** [comment]
You can open the Developer Tools (<kbd>Cmd+Opt+I</kbd> on MacOS) to get a more detailed error stack.

**Comment by metasean** [comment]
@ldez - I've never seen error stacks in a browser's dev tools (I assume you mean the console tab of the dev tools) when running a command from another app (e.g. Atom) or the terminal (running bash at the moment).  How do I get the output from a non-browser app to show up in the browser console?

**Comment by boggle** [comment]
I had to nuke all packages and re-install. This works though.
